=== lollisoft/lbdmf_oldCVSBranch/Test/Console/XML/lbxmlconfig.dtd
<!--
    DMF Distributed Multiplatform Framework (the initial goal of this library)
    lbModule.h is part of DMF.
    Copyright (C) 2002  Lothar Behrens (lothar.behrens@lollisoft.de)

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


    The author of this work will be reached by e-Mail or paper mail.
    e-Mail: lothar.behrens@lollisoft.de
    p-Mail: Lothar Behrens
            Borsteler Bogen 4

            22453 Hamburg (germany)
-->
<!ELEMENT dtdHostCfgDoc     ( Busmaster, StandardFunctor*, Modules* )>
<!ATTLIST dtdHostCfgDoc VERSION            CDATA  #IMPLIED >


<!ELEMENT Modules        (Module*)>
<!ATTLIST Modules        GroupDescription CDATA #FIXED "No description yet" >

<!--...sDocu to LOCID:0:-->
<!-- 
The name of a module is unique, because a module may only once
declared for an application. So ID is possible here. And the
IDPtr is not needed, because the SAX parser does this validation.

LOCID is a descriptor, explaining that in this subtree, all
FunctionName tags contain an unique identifer. The identiver itself
must be described in that tag.
-->
<!--...e-->
<!ELEMENT Module         (ModuleName, Functions*)>
<!ATTLIST Module         LOCID    CDATA      #FIXED "FunctionName" >

<!ELEMENT Functions      (Function*)>
<!ATTLIST Functions      GroupDescription CDATA #FIXED "No description yet" >

<!ELEMENT Function       (FunctionName, (Functor|SimpleFn))>
<!ATTLIST Function       Description      CDATA #FIXED "No description yet" >

<!ELEMENT Functor        (InterfaceName)>
<!ATTLIST Functor        Description      CDATA #FIXED "No description yet" >

<!--...sBusmaster:0:-->
<!ELEMENT Busmaster      (#PCDATA)>
<!ATTLIST Busmaster         ID             ID         #IMPLIED 
                            Hostname       CDATA      #IMPLIED 
                            Port           CDATA      #IMPLIED 
                            Description    CDATA      #IMPLIED >
<!--...e-->
<!--...sStandardFunctor:0:-->
<!ELEMENT StandardFunctor      (#PCDATA)>
<!ATTLIST StandardFunctor   ID             ID         #IMPLIED 
                            Interface      CDATA      #IMPLIED 
                            Functor        CDATA      #IMPLIED 
                            Module         CDATA      #IMPLIED
                            Typ            CDATA      #IMPLIED >
<!--...e-->
<!--...sModuleName:0:-->
<!ELEMENT ModuleName         (#PCDATA)>
<!ATTLIST ModuleName         Name     ID         #IMPLIED >
<!--...e-->
<!--...sFunctionName:0:-->
<!ELEMENT FunctionName          (#PCDATA)>
<!ATTLIST FunctionName       Name     CDATA       #IMPLIED 
                             IDPtr    CDATA       #FIXED "Name" >
<!--...e-->
<!--...sInterfaceName:0:-->
<!ELEMENT InterfaceName          (#PCDATA)>
<!ATTLIST InterfaceName      Name     CDATA       #IMPLIED 
                             Version  CDATA       #IMPLIED
                             IDPtr    CDATA       #FIXED "Name" >
<!--...e-->
<!--...sSimpleFn:0:-->
<!ELEMENT SimpleFn       (#PCDATA)>
<!ATTLIST SimpleFn       Return    CDATA      #IMPLIED >
<!--...e-->

=== lollisoft/lbdmf_oldCVSBranch/Test/Console/XML/lbxmlconfig.xml
<?xml version="1.0"?>
<!DOCTYPE dtdHostCfgDoc SYSTEM "lbXMLConfig.dtd">

<dtdHostCfgDoc VERSION="1.0.0">
  <Busmaster ID="ID1" Hostname="localhost" Port="5001" Description="Any description" />
<!--
  <BootstrapModule Name="lbClasses" />
-->

<!--
  A possible better way may a mapping from interfaces to their functors like this:
  
  <Map Interface="lb_I_Log" Module="lbclasses" Functor="..." />
  
  But in this way a mapping can contain multiple entries of the same mapping.
  
-->

  <StandardFunctor 
    Interface="lb_I_String" 
    Functor="_instanceOfString@4"
    Module="lbclasses" />
  <StandardFunctor 
    Interface="lb_I_Integer" 
    Functor="_instanceOfInteger@4"
    Module="lbclasses" />
  <StandardFunctor 
    Interface="lb_I_Long" 
    Functor="_instanceOfLong@4"
    Module="lbclasses" />
  
<!--...sModules:2:-->
  <Modules>
    <Module>
<!--...sModuleName lbclasses:8:-->
      <ModuleName Name="lbclasses"/>
<!--...e-->
<!--...sFunctions:8:-->
      <Functions>
<!--...sFunction instanceOfContainer:16:-->
        <Function>
           <FunctionName Name="_instanceOfContainer@4"/>
           <Functor>
              <InterfaceName Name="lb_I_Container" Version="1.0"/>
           </Functor>
        </Function>
<!--...e-->
<!--...sFunction instanceOfLogger:16:-->
        <Function>
           <FunctionName Name="_instanceOfLogger@4"/>
           <Functor>
              <InterfaceName Name="lb_I_Log" Version="1.0"/>
           </Functor>
        </Function>
<!--...e-->
<!--...sFunction instanceOfIntegerKey:16:-->
        <Function>
           <FunctionName Name="_instanceOfIntegerKey@4"/>
           <Functor>
              <InterfaceName Name="lb_I_KeyBase" Version="1.0"/>
           </Functor>
        </Function>
<!--...e-->
<!--...sFunction instanceOfInteger:16:-->
        <Function>
           <FunctionName Name="_instanceOfInteger@4"/>
           <Functor>
              <InterfaceName Name="lb_I_Integer" Version="1.0"/>
           </Functor>
        </Function>
<!--...e-->
<!--...sFunction instanceOfString:16:-->
        <Function>
           <FunctionName Name="_instanceOfString@4"/>
           <Functor>
              <InterfaceName Name="lb_I_String" Version="1.0"/>
           </Functor>
        </Function>
<!--...e-->
<!--...sFunction:16:-->
        <Function>
           <FunctionName Name="Function2"/>
           <SimpleFn     Return="lbString"/>
        </Function>
<!--...e-->
      </Functions>
<!--...e-->
    </Module>
    <Module>
<!--...sModuleName:8:-->
      <ModuleName Name="library2">
      </ModuleName>
<!--...e-->
<!--...sFunctions:8:-->
      <Functions>
<!--...sFunction:16:-->
        <Function>
           <FunctionName Name="Function3"/>
           <SimpleFn     Return="lbString"/>
        </Function>
<!--...e-->
      </Functions>
<!--...e-->
    </Module>
  </Modules>  
<!--...e-->
</dtdHostCfgDoc>
